### ISSUE TITLE
Failed to activate the instacodes-plugin package

### ISSUE THREAD

**Issue by djallits** [arandilopez/instacod.es-plugin#1]
[Enter steps to reproduce below:]
1. Install Package from Atom UI interface. 

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [instacodes-plugin](https://github.com/arandilopez/instacod.es-plugin) package, v0.0.2
### Stack Trace

Failed to activate the instacodes-plugin package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/Dan/.atom/packages/instacodes-plugin/lib/instacodes.coffee:7:23)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /opt/homebrew-cask/Caskroom/atom/1.6.2/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "php-hyperclick",
      "hyperclick"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-autocomplete-php, v0.18.9
auto-detect-indentation, v1.0.0
editor-stats, v0.17.0
editorconfig, v1.4.1
file-icons, v1.7.12
highlight-line, v0.11.1
instacodes-plugin, v0.0.2
linter, v1.11.4
linter-csslint, v1.3.2
linter-js-yaml, v1.2.5
linter-jshint, v2.1.0
linter-php, v1.2.0
linter-phpcs, v1.4.0
linter-phpmd, v1.4.1
minimap, v4.24.1
pigments, v0.26.3
project-manager, v2.9.7

# Dev
No dev packages
```

**Comment by arandilopez** [comment]
Thank you. I'll be working on this soon 🙂

**Comment by kurybr** [comment]
+1 I Have this error too

**Comment by ghost** [comment]
me too

**Comment by searge** [comment]
+1
